name: "Build & Test"

on:
  push:

jobs:
  examples:
    runs-on: macos-latest
    steps:
    - run: sudo rm -rf /opt&
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v26
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v14
      with:
        name: cachix-test
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        installCommand: nix profile install github:cachix/cachix -L --accept-flake-config
    - run: |
        nix build
        PATH=$PWD/result/bin:$PATH devenv-run-tests --only imports examples
