name: "Build & Test"

on:
  push:

jobs:
  examples:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      with:
        detached: true
    - uses: cachix/install-nix-action@v26
      # with:
      #   extra_nix_config: |
      #     access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@master
      with:
        name: cachix-test
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        installCommand: nix profile install github:cachix/cachix/debug-daemon-stop -L --accept-flake-config
        cachixArgs: --verbose
    - run: |
        nix build
        PATH=$PWD/result/bin:$PATH devenv-run-tests --only imports examples
